# Generated by Django 4.1.7 on 2023-03-01 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_contract_sales_contact_alter_client_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(500)]),
        ),
    ]
