# Generated by Django 4.1.7 on 2023-03-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_client_sales_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='closed',
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='customer_satisfaction',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_retrospective',
            field=models.TextField(),
        ),
    ]
