# Generated by Django 4.1.7 on 2023-03-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_attendees_alter_event_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='mobile',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
