# Generated by Django 4.1.7 on 2023-03-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_mobile_client_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='date',
        ),
    ]
