# Generated by Django 4.1.7 on 2023-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_event_date_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
